import scrapy

class TenderItem(scrapy.Item):
    tenderId = scrapy.Field()
    sourceUrl = scrapy.Field()
    scrapedTimestamp = scrapy.Field()
    country = scrapy.Field()
    state = scrapy.Field()
    region = scrapy.Field()
    referenceNumber = scrapy.Field()
    title = scrapy.Field()
    issuingAuthority = scrapy.Field()
    procurementSummary = scrapy.Field()
    category = scrapy.Field()
    tenderValue = scrapy.Field()
    currency = scrapy.Field()
    publishedDate = scrapy.Field()
    clarificationEndDate = scrapy.Field()
    closingDate = scrapy.Field()
    openingDate = scrapy.Field()
    eligibilityRequirements = scrapy.Field()
    proposalFormat = scrapy.Field()
    unstructuredData = scrapy.Field()
    vectorEmbedding = scrapy.Field()
